"""Add AI-reasoning attribution columns to opportunity_reminders.

TASK-0021 (SPEC-0003 v0.3.0): ``ai_used`` / ``external_egress`` record
truthfully whether the shown supporting reason was generated by an external
model and whether an egress call was attempted (R-020/AC-017); ``model_identifier``
and ``egress_field_names`` (field names, never values) support the R-019 audit.

This migration is local synthetic only — no production database is touched.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0005_opportunity_reminders_ai_reasoning"
down_revision: str | None = "0004_opportunity_reminders"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "opportunity_reminders",
        sa.Column(
            "ai_used",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "opportunity_reminders",
        sa.Column(
            "external_egress",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "opportunity_reminders",
        sa.Column("model_identifier", sa.String(120), nullable=True),
    )
    op.add_column(
        "opportunity_reminders",
        sa.Column("egress_field_names", sa.JSON(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("opportunity_reminders", "egress_field_names")
    op.drop_column("opportunity_reminders", "model_identifier")
    op.drop_column("opportunity_reminders", "external_egress")
    op.drop_column("opportunity_reminders", "ai_used")
