// 演示·暖阳居家养老服务中心（模拟机构） · 核心数据字典与拟真数据集
// 依据：docs/HOME-CARE-SPEC.md 与 docs/PLATFORM-SPEC.md §4 (elderly_care_org)
// 严禁脱敏星号，杜绝任何占位符；72位社区长者全部真实具名、真实门牌、真实设备遥测

export interface GridCommunityArea {
  key: 'canglang' | 'shuangta' | 'sanxiang'
  name: string
  streetName: string
  leadCaregiverName: string
  leadCaregiverPhone: string
  stationAddress: string
  communities: string[]
}

export const GRID_AREAS: Record<string, GridCommunityArea> = {
  canglang: {
    key: 'canglang',
    name: '沧浪片区',
    streetName: '演示市城南示范区沧浪街道',
    leadCaregiverName: '林小燕',
    leadCaregiverPhone: '13913508821',
    stationAddress: '沧浪新村 16 幢底层社区助老综合服务分站',
    communities: ['沧浪新村第一网格', '沧浪新村第二网格', '竹辉社区网格', '道前社区网格'],
  },
  shuangta: {
    key: 'shuangta',
    name: '双塔片区',
    streetName: '演示市城南示范区双塔街道',
    leadCaregiverName: '王惠芬',
    leadCaregiverPhone: '13812760934',
    stationAddress: '十全街 208 号双塔综合为老服务分中心',
    communities: ['滚绣坊社区网格', '沧浪亭社区网格', '网师巷社区网格', '带城桥社区网格'],
  },
  sanxiang: {
    key: 'sanxiang',
    name: '三香片区',
    streetName: '演示市城南示范区金阊/三香网格',
    leadCaregiverName: '何丽娜',
    leadCaregiverPhone: '13771982341',
    stationAddress: '三香路 412 号三香为老便民服务驿站',
    communities: ['三香社区北区网格', '三香社区南区网格', '体育场社区网格', '盘溪社区网格'],
  },
}

export type HomeStaffCategory = 'caregiver' | 'idt_medical' | 'qa_manager'

export interface GridCaregiver {
  id: string
  name: string
  gender: 'male' | 'female'
  phone: string
  areaKey: 'all' | 'canglang' | 'shuangta' | 'sanxiang'
  areaName: string
  category: HomeStaffCategory
  categoryLabel: string
  roleTitle: string
  avatar: string
  onDuty: boolean
  assignedTitle: string
  managedElderCount: number
  pendingWorkOrders: number
  skills: string[]
  credentials?: string[]
  note?: string
}

export const GRID_CAREGIVERS: GridCaregiver[] = [
  // ==================== 1. 社区网格助老团队 ====================
  // 沧浪片区
  {
    id: 'demo_grid_caregiver_01',
    name: '林小燕',
    gender: 'female',
    phone: '13913508821',
    areaKey: 'canglang',
    areaName: '沧浪片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '高级助老员',
    avatar: '👩‍⚕️',
    onDuty: true,
    assignedTitle: '高级助老员 (沧浪片区骨干)',
    managedElderCount: 13,
    pendingWorkOrders: 4,
    skills: ['重度失能介护', '床上温水擦浴', '压疮防范翻身', '生命体征感知'],
    credentials: ['五级养老护理员', '红十字急救员证'],
  },
  {
    id: 'demo_caregiver_02',
    name: '陈秀英',
    gender: 'female',
    phone: '13814892015',
    areaKey: 'canglang',
    areaName: '沧浪片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '中级养老照护师',
    avatar: '👩‍⚕️',
    onDuty: true,
    assignedTitle: '中级养老照护师',
    managedElderCount: 12,
    pendingWorkOrders: 3,
    skills: ['生活起居照护', '慢病用药辅导', '助餐助洁', '心理慰藉'],
    credentials: ['中级养老照护师'],
  },
  {
    id: 'demo_caregiver_03',
    name: '黄建国',
    gender: 'male',
    phone: '13606214578',
    areaKey: 'canglang',
    areaName: '沧浪片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '当值机动助老员',
    avatar: '👨‍⚕️',
    onDuty: true,
    assignedTitle: '当值机动助老员 (应急响应)',
    managedElderCount: 7,
    pendingWorkOrders: 2,
    skills: ['突发跌倒排查', '安居设备检修', '重度协助转移', '夜巡机动'],
    credentials: ['初级照护员', '急救先锋认证'],
  },
  {
    id: 'demo_caregiver_04',
    name: '周玉兰',
    gender: 'female',
    phone: '13771903348',
    areaKey: 'canglang',
    areaName: '沧浪片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '初级助老员',
    avatar: '👩‍⚕️',
    onDuty: false, // 今日轮休
    assignedTitle: '初级助老员 (今日轮休)',
    managedElderCount: 0,
    pendingWorkOrders: 0,
    skills: ['生活起居照料', '日常居室清洁'],
    credentials: ['初级养老护理员'],
    note: '今日排班轮休，所分管长者已交接由林小燕、陈秀英代管',
  },

  // 双塔片区
  {
    id: 'cg_shuangta_01',
    name: '王惠芬',
    gender: 'female',
    phone: '13812760934',
    areaKey: 'shuangta',
    areaName: '双塔片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '片区组长 (高级照护师)',
    avatar: '👩‍⚕️',
    onDuty: true,
    assignedTitle: '双塔片区组长 (高级养老照护师)',
    managedElderCount: 14,
    pendingWorkOrders: 5,
    skills: ['全科照护管理', '重度卧床翻身', '康复协助', '工单督导'],
    credentials: ['高级养老护理员', '双塔服务站副站长'],
  },
  {
    id: 'cg_shuangta_02',
    name: '张伟民',
    gender: 'male',
    phone: '13912648721',
    areaKey: 'shuangta',
    areaName: '双塔片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '养老照护员',
    avatar: '👨‍⚕️',
    onDuty: true,
    assignedTitle: '养老照护员',
    managedElderCount: 13,
    pendingWorkOrders: 4,
    skills: ['助浴协助', '轮椅转运', '生活照护', '居家水电气排查'],
    credentials: ['初级照护员'],
  },

  // 三香片区
  {
    id: 'cg_sanxiang_01',
    name: '何丽娜',
    gender: 'female',
    phone: '13771982341',
    areaKey: 'sanxiang',
    areaName: '三香片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '慢病照护员 (主管护师)',
    avatar: '👩‍⚕️',
    onDuty: true,
    assignedTitle: '慢病照护专员 (主管护师)',
    managedElderCount: 13,
    pendingWorkOrders: 4,
    skills: ['慢病健康监测', '血压血糖管理', '造口导尿管维护', '认知症陪护'],
    credentials: ['主管护师 (中级)', '慢病健康管理专员'],
  },
  {
    id: 'cg_sanxiang_02',
    name: '赵淑清',
    gender: 'female',
    phone: '13862109432',
    areaKey: 'sanxiang',
    areaName: '三香片区',
    category: 'caregiver',
    categoryLabel: '片区助老员',
    roleTitle: '助老员',
    avatar: '👩‍⚕️',
    onDuty: true,
    assignedTitle: '助老员',
    managedElderCount: 12,
    pendingWorkOrders: 3,
    skills: ['生活照护', '助餐助洁', '空巢探访', '心理支持'],
    credentials: ['初级照护员'],
  },

  // ==================== 2. 多学科专业支撑团队 (IDT · 对标福寿康医护康) ====================
  {
    id: 'demo_nurse_shen',
    name: '沈雅萍',
    gender: 'female',
    phone: '13912683012',
    areaKey: 'all',
    areaName: '全区医疗巡诊',
    category: 'idt_medical',
    categoryLabel: '居家专职护师',
    roleTitle: '主管护师 (专职护师)',
    avatar: '👩‍⚕️',
    onDuty: true,
    assignedTitle: '居家医疗护理站长 / 专职护师',
    managedElderCount: 18,
    pendingWorkOrders: 5,
    skills: ['留置导尿与胃管更换', 'IV期复杂压疮清创换药', '造口专项护理', '胰岛素注射指导', '静脉采血与慢病配药'],
    credentials: ['主管护师 (中级)', '国际伤口造口治疗师 (ET)', '中华护理学会上门护士认证'],
  },
  {
    id: 'pt_chenjianxin',
    name: '陈建新',
    gender: 'male',
    phone: '13862015598',
    areaKey: 'all',
    areaName: '全区康复巡诊',
    category: 'idt_medical',
    categoryLabel: '康复治疗师',
    roleTitle: '主管康复师 (PT主管)',
    avatar: '👨‍⚕️',
    onDuty: true,
    assignedTitle: '居家康复治疗师 (PT主管)',
    managedElderCount: 14,
    pendingWorkOrders: 4,
    skills: ['脑卒中偏瘫肢体综合训练', '关节活动度维持 (ROM)', '平衡与步态再训练', '助行器与轮椅适配评估'],
    credentials: ['主管康复治疗师', '中国康复医学会认证PT', '老年运动障碍康复专家'],
  },
  {
    id: 'dementia_zhufang',
    name: '朱芳',
    gender: 'female',
    phone: '13771890214',
    areaKey: 'all',
    areaName: '全区记忆专案',
    category: 'idt_medical',
    categoryLabel: '认知症专护',
    roleTitle: '记忆照护专护师',
    avatar: '👩‍🦰',
    onDuty: true,
    assignedTitle: '记忆照护与认知症专护师',
    managedElderCount: 11,
    pendingWorkOrders: 3,
    skills: ['认知症非药物怀旧疗法', '防走失雷达围栏配置', '蒙台梭利老年失智干预', '家庭照护者减压督导'],
    credentials: ['高级老年照护师', '阿尔茨海默病照护协会认证专员', '心理疏导员二级'],
  },
  {
    id: 'tech_zhanghongbo',
    name: '张洪波',
    gender: 'male',
    phone: '13616238841',
    areaKey: 'all',
    areaName: '适老辅具工程',
    category: 'idt_medical',
    categoryLabel: '辅具适老顾问',
    roleTitle: '适老辅具工程师',
    avatar: '👨‍🔧',
    onDuty: true,
    assignedTitle: '适老化改造与辅具工程师',
    managedElderCount: 22,
    pendingWorkOrders: 3,
    skills: ['家庭无障碍环境评估', '防滑扶手/卫浴无障碍施工', '60GHz毫米波雷达排障', '电动护理床/轮椅调试与租赁'],
    credentials: ['康复辅助器具适配工程师', '老年人居家适老化改造评估员'],
  },

  // ==================== 3. 连锁质控督导与长护险风控部 (对标居家乐质控生命线) ====================
  {
    id: 'qc_jiangguoqiang',
    name: '蒋国强',
    gender: 'male',
    phone: '13806201389',
    areaKey: 'all',
    areaName: '全域质控督导',
    category: 'qa_manager',
    categoryLabel: '质控督导主管',
    roleTitle: '质量督导部主管',
    avatar: '👨‍💼',
    onDuty: true,
    assignedTitle: '质量督导部主管 / 资深质检员',
    managedElderCount: 72,
    pendingWorkOrders: 4,
    skills: ['入户现场双盲飞行检查', '12349电话回访100%录音质检', '打卡轨迹与雷达防虚构核验', '照护质量违规整改督导'],
    credentials: ['高级质量管理工程师', '苏州市居家养老服务质控评估员'],
  },
  {
    id: 'cm_xumeiling',
    name: '徐美玲',
    gender: 'female',
    phone: '13915579902',
    areaKey: 'all',
    areaName: '个案协同管理',
    category: 'qa_manager',
    categoryLabel: '个案管理师',
    roleTitle: '养老管家 / 个案管理师',
    avatar: '👩‍💼',
    onDuty: true,
    assignedTitle: '养老管家 / 个案管理师 (Care Coordinator)',
    managedElderCount: 36,
    pendingWorkOrders: 6,
    skills: ['“一人一策”照护计划定制', '长护险定点服务初筛建档', '多学科团队IDT联合派单', '家属满意度全流程随访'],
    credentials: ['中级社会工作师 (社工师)', '国家健康管理师二级'],
  },
  {
    id: 'biller_zhouliping',
    name: '周立平',
    gender: 'male',
    phone: '13962145520',
    areaKey: 'all',
    areaName: '医保结算风控',
    category: 'qa_manager',
    categoryLabel: '长护险结算风控',
    roleTitle: '长护险结算主管',
    avatar: '👨‍💻',
    onDuty: true,
    assignedTitle: '长护险结算与风控专员',
    managedElderCount: 72,
    pendingWorkOrders: 2,
    skills: ['长护险服务工单月度比对核销', '医保基金统筹拨付申报', '个人自负收缴对账', '医保反虚构欺诈接口对接'],
    credentials: ['长护险结算审核资格证', '初级会计师'],
  },
]

export interface SmartDevicesConfig {
  radar_bathroom: {
    device_id: string
    online: boolean
    presence: boolean
    fall_alert: boolean
    signal_strength: string
    last_event: string
  }
  sleep_pad?: {
    device_id: string
    online: boolean
    in_bed: boolean
    hr: number
    br: number
    leave_bed_minutes: number
    sleep_score: number
  }
  sos_button: {
    device_id: string
    online: boolean
    battery_pct: number
    alarm_active: boolean
    last_test_date: string
  }
  gas_sensor?: {
    device_id: string
    online: boolean
    alarm: boolean
  }
  door_sensor?: {
    device_id: string
    online: boolean
    is_open: boolean
    last_open_time: string
  }
}

export interface HomeElderly {
  elderly_id: string
  name: string
  gender: 'male' | 'female'
  age: number
  id_card: string
  phone: string
  area_key: 'canglang' | 'shuangta' | 'sanxiang'
  area_name: string
  community_name: string
  home_address: string
  has_elevator: boolean
  floor_number: number
  ltc_level: '重度失能' | '中度失能' | '轻度失能' | '自理高龄'
  living_status: '独居' | '空巢' | '与子女同住'
  current_state: '在家长者' | '异常预警' | '外出活动' | '失联排查'
  assigned_caregiver_id: string
  assigned_caregiver_name: string
  emergency_contact: {
    name: string
    relation: string
    phone: string
    address: string
  }
  chronic_diseases: string[]
  care_risk_tags: string[]
  devices: SmartDevicesConfig
  monthly_service_quota: number
  monthly_service_completed: number
  last_service_time: string
  next_service_plan: string
}

// 真实具名 72 位社区长者全量数据集（沧浪片区 26位，双塔片区 26位，三香片区 20位）
export const HOME_ELDERS: HomeElderly[] = [
  // ================= 沧浪片区 (26人) =================
  {
    elderly_id: 'SZ-ELD-10001',
    name: '张卫国',
    gender: 'male',
    age: 82,
    id_card: '320502194403152018',
    phone: '0512-65231892',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '沧浪新村第一网格',
    home_address: '沧浪新村 12 幢 302 室',
    has_elevator: false,
    floor_number: 3,
    ltc_level: '重度失能',
    living_status: '独居',
    current_state: '在家长者',
    assigned_caregiver_id: 'demo_grid_caregiver_01',
    assigned_caregiver_name: '林小燕',
    emergency_contact: {
      name: '张志明',
      relation: '长子',
      phone: '13812694582',
      address: '苏州市工业园区玲珑湾花园 8 幢 601 室',
    },
    chronic_diseases: ['脑梗死后遗症偏瘫', '高血压病III期', '冠状动脉粥样硬化'],
    care_risk_tags: ['高跌倒风险', '防压疮重点', '独居重点看护'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0012',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-58dBm)',
        last_event: '今日 07:15 卫浴活动正常离开',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1082',
        online: true,
        in_bed: true,
        hr: 68,
        br: 16,
        leave_bed_minutes: 0,
        sleep_score: 84,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9011',
        online: true,
        battery_pct: 92,
        alarm_active: false,
        last_test_date: '2026-09-20',
      },
      gas_sensor: {
        device_id: 'GAS-SZ-CL-012',
        online: true,
        alarm: false,
      },
      door_sensor: {
        device_id: 'DOOR-SZ-CL-012',
        online: true,
        is_open: false,
        last_open_time: '昨日 18:30',
      },
    },
    monthly_service_quota: 20,
    monthly_service_completed: 16,
    last_service_time: '2026-09-24 14:30',
    next_service_plan: '今日 09:30 床上擦浴与防压疮翻身护理',
  },
  {
    elderly_id: 'SZ-ELD-10002',
    name: '孙秀珍',
    gender: 'female',
    age: 85,
    id_card: '320502194107281523',
    phone: '13912783301',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '竹辉社区网格',
    home_address: '竹辉新村 28 幢 101 室',
    has_elevator: false,
    floor_number: 1,
    ltc_level: '重度失能',
    living_status: '空巢',
    current_state: '异常预警', // 离床超时
    assigned_caregiver_id: 'demo_caregiver_02',
    assigned_caregiver_name: '陈秀英',
    emergency_contact: {
      name: '陆晓平',
      relation: '女儿',
      phone: '13912783301',
      address: '演示市城南示范区南门水岸名苑 5 幢 1204 室',
    },
    chronic_diseases: ['阿尔茨海默病 (中度认知障碍)', '高血压病II期', '骨质疏松伴活动受限'],
    care_risk_tags: ['防走失高危', '夜间离床超时', '跌倒高危'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0028',
        online: true,
        presence: true,
        fall_alert: false,
        signal_strength: '强 (-62dBm)',
        last_event: '今日 04:20 进入卫浴间滞留超过 25 分钟',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1090',
        online: true,
        in_bed: false,
        hr: 74,
        br: 18,
        leave_bed_minutes: 75,
        sleep_score: 62,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9028',
        online: true,
        battery_pct: 88,
        alarm_active: false,
        last_test_date: '2026-09-18',
      },
      door_sensor: {
        device_id: 'DOOR-SZ-CL-028',
        online: true,
        is_open: true,
        last_open_time: '今日 04:15 进户门开启',
      },
    },
    monthly_service_quota: 20,
    monthly_service_completed: 17,
    last_service_time: '2026-09-24 16:00',
    next_service_plan: '今日 08:30 认知症陪伴及起居安全巡视',
  },
  {
    elderly_id: 'SZ-ELD-10003',
    name: '李德海',
    gender: 'male',
    age: 79,
    id_card: '320502194711093415',
    phone: '0512-65112093',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '沧浪新村第一网格',
    home_address: '沧浪新村 7 幢 201 室',
    has_elevator: false,
    floor_number: 2,
    ltc_level: '中度失能',
    living_status: '与子女同住',
    current_state: '在家长者',
    assigned_caregiver_id: 'demo_grid_caregiver_01',
    assigned_caregiver_name: '林小燕',
    emergency_contact: {
      name: '李建峰',
      relation: '次子',
      phone: '13771890245',
      address: '沧浪新村 7 幢 201 室 (共同居住)',
    },
    chronic_diseases: ['帕金森病', '前列腺增生伴排尿障碍'],
    care_risk_tags: ['肢体震颤防跌倒', '步态不稳'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0007',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-60dBm)',
        last_event: '今日 06:40 卫浴正常出入',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1095',
        online: true,
        in_bed: true,
        hr: 70,
        br: 15,
        leave_bed_minutes: 0,
        sleep_score: 80,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9007',
        online: true,
        battery_pct: 95,
        alarm_active: false,
        last_test_date: '2026-09-21',
      },
    },
    monthly_service_quota: 15,
    monthly_service_completed: 12,
    last_service_time: '2026-09-23 10:15',
    next_service_plan: '今日 10:45 助洁与下床移位肢体功能维护',
  },
  {
    elderly_id: 'SZ-ELD-10004',
    name: '周秉坤',
    gender: 'male',
    age: 76,
    id_card: '320502195004122119',
    phone: '13656201948',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '道前社区网格',
    home_address: '西美巷 45 号 2 楼',
    has_elevator: false,
    floor_number: 2,
    ltc_level: '轻度失能',
    living_status: '独居',
    current_state: '外出活动',
    assigned_caregiver_id: 'demo_grid_caregiver_01',
    assigned_caregiver_name: '林小燕',
    emergency_contact: {
      name: '周丽敏',
      relation: '长女',
      phone: '13962140023',
      address: '苏州市相城区元和街道华元花园 12 幢',
    },
    chronic_diseases: ['高血压病II期', '轻度腰椎间盘突出'],
    care_risk_tags: ['独居定期探访', '居家用气安全'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0045',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-55dBm)',
        last_event: '昨日 21:00 卫浴正常',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1102',
        online: true,
        in_bed: false,
        hr: 0,
        br: 0,
        leave_bed_minutes: 180,
        sleep_score: 86,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9045',
        online: true,
        battery_pct: 90,
        alarm_active: false,
        last_test_date: '2026-09-22',
      },
      door_sensor: {
        device_id: 'DOOR-SZ-CL-045',
        online: true,
        is_open: false,
        last_open_time: '今日 06:20 出门买早点',
      },
    },
    monthly_service_quota: 10,
    monthly_service_completed: 8,
    last_service_time: '2026-09-22 15:00',
    next_service_plan: '明日 09:00 居家用气线路排查与慢病血压测量',
  },
  {
    elderly_id: 'SZ-ELD-10005',
    name: '杨保国',
    gender: 'male',
    age: 88,
    id_card: '320502193809051012',
    phone: '0512-65228190',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '沧浪新村第二网格',
    home_address: '沧浪新村 35 幢 102 室',
    has_elevator: false,
    floor_number: 1,
    ltc_level: '重度失能',
    living_status: '空巢',
    current_state: '在家长者',
    assigned_caregiver_id: 'demo_caregiver_02',
    assigned_caregiver_name: '陈秀英',
    emergency_contact: {
      name: '杨红兵',
      relation: '儿子',
      phone: '13812890123',
      address: '苏州市高新区狮山新苑 6 幢',
    },
    chronic_diseases: ['慢性心力衰竭', '长期卧床', '重度骨关节挛缩'],
    care_risk_tags: ['防压疮重点', '低氧血症关注', '吸入性肺炎风险'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0035',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-57dBm)',
        last_event: '正常',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1110',
        online: true,
        in_bed: true,
        hr: 76,
        br: 19,
        leave_bed_minutes: 0,
        sleep_score: 75,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9035',
        online: true,
        battery_pct: 94,
        alarm_active: false,
        last_test_date: '2026-09-19',
      },
    },
    monthly_service_quota: 20,
    monthly_service_completed: 18,
    last_service_time: '2026-09-24 09:00',
    next_service_plan: '今日 14:00 全身翻身防压疮护理与呼吸道吸痰协助',
  },
  {
    elderly_id: 'SZ-ELD-10006',
    name: '王素芬',
    gender: 'female',
    age: 86,
    id_card: '320502194002181224',
    phone: '13812604921',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '竹辉社区网格',
    home_address: '南门水岸名苑 3 幢 501 室',
    has_elevator: true,
    floor_number: 5,
    ltc_level: '重度失能',
    living_status: '独居',
    current_state: '在家长者',
    assigned_caregiver_id: 'demo_caregiver_02',
    assigned_caregiver_name: '陈秀英',
    emergency_contact: {
      name: '陈建华',
      relation: '女婿',
      phone: '13913589920',
      address: '演示市城南示范区竹辉路 188 号',
    },
    chronic_diseases: ['脑出血恢复期', '吞咽功能减退', '重度白内障'],
    care_risk_tags: ['误吸噎食风险', '高跌倒风险'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0050',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-53dBm)',
        last_event: '正常',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1115',
        online: true,
        in_bed: true,
        hr: 72,
        br: 17,
        leave_bed_minutes: 0,
        sleep_score: 82,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9050',
        online: true,
        battery_pct: 91,
        alarm_active: false,
        last_test_date: '2026-09-23',
      },
    },
    monthly_service_quota: 20,
    monthly_service_completed: 15,
    last_service_time: '2026-09-24 11:30',
    next_service_plan: '今日 15:30 进食协助与面部手足部清洁',
  },
  {
    elderly_id: 'SZ-ELD-10007',
    name: '郭振华',
    gender: 'male',
    age: 84,
    id_card: '320502194206141819',
    phone: '0512-65290142',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '沧浪新村第一网格',
    home_address: '沧浪新村 18 幢 402 室',
    has_elevator: false,
    floor_number: 4,
    ltc_level: '重度失能',
    living_status: '独居',
    current_state: '异常预警', // 卫浴突发跌倒告警中
    assigned_caregiver_id: 'demo_caregiver_03',
    assigned_caregiver_name: '黄建国',
    emergency_contact: {
      name: '郭伟',
      relation: '长子',
      phone: '13706209841',
      address: '苏州市工业园区东沙湖名轩 4 幢',
    },
    chronic_diseases: ['心律失常 (室性早搏)', '重度骨性关节炎', '脑缺血发作史'],
    care_risk_tags: ['毫米波卫浴跌倒', '独居紧急响应'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0018',
        online: true,
        presence: true,
        fall_alert: true, // 跌倒告警
        signal_strength: '强 (-59dBm)',
        last_event: '今日 07:42 卫浴间突发急速下坠，未自行站起',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1120',
        online: true,
        in_bed: false,
        hr: 92,
        br: 22,
        leave_bed_minutes: 35,
        sleep_score: 70,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9018',
        online: true,
        battery_pct: 85,
        alarm_active: true, // 拉绳已被触发
        last_test_date: '2026-09-24',
      },
    },
    monthly_service_quota: 20,
    monthly_service_completed: 16,
    last_service_time: '2026-09-23 16:30',
    next_service_plan: '紧急工单：机动助老员黄建国正在上门现场排查跌倒',
  },
  {
    elderly_id: 'SZ-ELD-10008',
    name: '刘桂英',
    gender: 'female',
    age: 79,
    id_card: '320502194708221842',
    phone: '13862094182',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '道前社区网格',
    home_address: '剪金街 88 号 1 楼',
    has_elevator: false,
    floor_number: 1,
    ltc_level: '中度失能',
    living_status: '空巢',
    current_state: '在家长者',
    assigned_caregiver_id: 'demo_grid_caregiver_01',
    assigned_caregiver_name: '林小燕',
    emergency_contact: {
      name: '宋建国',
      relation: '老伴',
      phone: '13862094183',
      address: '剪金街 88 号 1 楼 (同住)',
    },
    chronic_diseases: ['糖尿病周围神经病变', '视力障碍'],
    care_risk_tags: ['防烫伤', '防磕碰'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0088',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-63dBm)',
        last_event: '正常',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1125',
        online: true,
        in_bed: true,
        hr: 66,
        br: 16,
        leave_bed_minutes: 0,
        sleep_score: 88,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9088',
        online: true,
        battery_pct: 94,
        alarm_active: false,
        last_test_date: '2026-09-17',
      },
    },
    monthly_service_quota: 15,
    monthly_service_completed: 13,
    last_service_time: '2026-09-24 10:00',
    next_service_plan: '今日 16:30 血糖监测及足部皮肤护理',
  },
  {
    elderly_id: 'SZ-ELD-10009',
    name: '胡广德',
    gender: 'male',
    age: 81,
    id_card: '320502194510031911',
    phone: '0512-65287319',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '沧浪新村第二网格',
    home_address: '沧浪新村 42 幢 301 室',
    has_elevator: false,
    floor_number: 3,
    ltc_level: '重度失能',
    living_status: '独居',
    current_state: '在家长者',
    assigned_caregiver_id: 'demo_grid_caregiver_01',
    assigned_caregiver_name: '林小燕',
    emergency_contact: {
      name: '胡建平',
      relation: '长子',
      phone: '13912658841',
      address: '演示市城南示范区人民路 1018 号',
    },
    chronic_diseases: ['前列腺癌术后', '慢性肾功能不全', '贫血'],
    care_risk_tags: ['排泄护理', '营养不良风险'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0042',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-61dBm)',
        last_event: '正常',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1130',
        online: true,
        in_bed: true,
        hr: 70,
        br: 17,
        leave_bed_minutes: 0,
        sleep_score: 79,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9042',
        online: true,
        battery_pct: 89,
        alarm_active: false,
        last_test_date: '2026-09-22',
      },
    },
    monthly_service_quota: 20,
    monthly_service_completed: 15,
    last_service_time: '2026-09-23 14:00',
    next_service_plan: '今日 11:15 会阴造口清洁冲洗与更衣',
  },
  {
    elderly_id: 'SZ-ELD-10010',
    name: '陈金秀',
    gender: 'female',
    age: 83,
    id_card: '320502194305191427',
    phone: '13812709124',
    area_key: 'canglang',
    area_name: '沧浪片区',
    community_name: '竹辉社区网格',
    home_address: '竹辉新村 15 幢 202 室',
    has_elevator: false,
    floor_number: 2,
    ltc_level: '中度失能',
    living_status: '空巢',
    current_state: '在家长者',
    assigned_caregiver_id: 'demo_caregiver_02',
    assigned_caregiver_name: '陈秀英',
    emergency_contact: {
      name: '李美琴',
      relation: '女儿',
      phone: '13912781190',
      address: '苏州市吴中区龙湖狮山天街 3 幢',
    },
    chronic_diseases: ['类风湿性关节炎', '骨盆骨折内固定术后'],
    care_risk_tags: ['轮椅转移协助', '防跌倒'],
    devices: {
      radar_bathroom: {
        device_id: 'RD-SZ-CL-0015',
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-56dBm)',
        last_event: '正常',
      },
      sleep_pad: {
        device_id: 'SP-SZ-CL-1135',
        online: true,
        in_bed: true,
        hr: 71,
        br: 16,
        leave_bed_minutes: 0,
        sleep_score: 83,
      },
      sos_button: {
        device_id: 'SOS-SZ-CL-9015',
        online: true,
        battery_pct: 93,
        alarm_active: false,
        last_test_date: '2026-09-20',
      },
    },
    monthly_service_quota: 15,
    monthly_service_completed: 13,
    last_service_time: '2026-09-24 15:30',
    next_service_plan: '今日 13:30 关节功能康复活动及助行协助',
  },
  // 沧浪片区其他真实长者 (10011 ~ 10026)
  ...[
    { id: 11, name: '钱福祥', gender: 'male', age: 77, ltc: '轻度失能', live: '与子女同住', addr: '沧浪新村 8 幢 101 室', cgId: 'demo_grid_caregiver_01', cgName: '林小燕' },
    { id: 12, name: '马玉兰', gender: 'female', age: 78, ltc: '自理高龄', live: '独居', addr: '西美巷 12 号 1 室', cgId: 'demo_grid_caregiver_01', cgName: '林小燕' },
    { id: 13, name: '徐建业', gender: 'male', age: 83, ltc: '重度失能', live: '空巢', addr: '竹辉新村 32 幢 301 室', cgId: 'demo_caregiver_02', cgName: '陈秀英' },
    { id: 14, name: '黄淑琴', gender: 'female', age: 89, ltc: '重度失能', live: '独居', addr: '南门水岸名苑 6 幢 402 室', cgId: 'demo_caregiver_02', cgName: '陈秀英' },
    { id: 15, name: '林宝山', gender: 'male', age: 80, ltc: '中度失能', live: '空巢', addr: '沧浪新村 22 幢 201 室', cgId: 'demo_grid_caregiver_01', cgName: '林小燕' },
    { id: 16, name: '高素云', gender: 'female', age: 81, ltc: '中度失能', live: '独居', addr: '剪金街 102 号 2 室', cgId: 'demo_caregiver_02', cgName: '陈秀英' },
    { id: 17, name: '罗长青', gender: 'male', age: 85, ltc: '重度失能', live: '独居', addr: '沧浪新村 48 幢 501 室', cgId: 'demo_caregiver_03', cgName: '黄建国' },
    { id: 18, name: '吴秀荣', gender: 'female', age: 75, ltc: '轻度失能', live: '与子女同住', addr: '竹辉新村 11 幢 201 室', cgId: 'demo_caregiver_02', cgName: '陈秀英' },
    { id: 19, name: '梁桂生', gender: 'male', age: 82, ltc: '重度失能', live: '独居', addr: '沧浪新村 19 幢 302 室', cgId: 'demo_caregiver_03', cgName: '黄建国' },
    { id: 20, name: '朱凤英', gender: 'female', age: 87, ltc: '重度失能', live: '空巢', addr: '西美巷 66 号', cgId: 'demo_grid_caregiver_01', cgName: '林小燕' },
    { id: 21, name: '宋明远', gender: 'male', age: 84, ltc: '中度失能', live: '独居', addr: '沧浪新村 30 幢 102 室', cgId: 'demo_caregiver_03', cgName: '黄建国' },
    { id: 22, name: '何爱华', gender: 'female', age: 82, ltc: '重度失能', live: '空巢', addr: '竹辉新村 40 幢 202 室', cgId: 'demo_caregiver_02', cgName: '陈秀英' },
    { id: 23, name: '郑树清', gender: 'male', age: 86, ltc: '重度失能', live: '独居', addr: '南门水岸名苑 1 幢 802 室', cgId: 'demo_caregiver_03', cgName: '黄建国' },
    { id: 24, name: '梁桂珍', gender: 'female', age: 80, ltc: '中度失能', live: '与子女同住', addr: '沧浪新村 14 幢 202 室', cgId: 'demo_grid_caregiver_01', cgName: '林小燕' },
    { id: 25, name: '韩世忠', gender: 'male', age: 79, ltc: '轻度失能', live: '独居', addr: '西美巷 38 号 2 楼', cgId: 'demo_caregiver_03', cgName: '黄建国' },
    { id: 26, name: '唐秀英', gender: 'female', age: 83, ltc: '重度失能', live: '独居', addr: '沧浪新村 27 幢 301 室', cgId: 'demo_grid_caregiver_01', cgName: '林小燕' },
  ].map((item, idx) => ({
    elderly_id: `SZ-ELD-100${item.id}`,
    name: item.name,
    gender: (item.gender as 'male' | 'female'),
    age: item.age,
    id_card: `320502${1940 + (idx % 12)}0${(idx % 9) + 1}15${1000 + item.id}`,
    phone: `13812${300000 + item.id * 111}`,
    area_key: ('canglang' as const),
    area_name: '沧浪片区',
    community_name: item.addr.includes('沧浪') ? '沧浪新村网格' : item.addr.includes('竹辉') ? '竹辉社区网格' : '道前社区网格',
    home_address: item.addr,
    has_elevator: item.addr.includes('南门水岸'),
    floor_number: Number(item.addr.match(/\d+ 室/)?.[0]?.charAt(0) || 2),
    ltc_level: (item.ltc as any),
    living_status: (item.live as any),
    current_state: ('在家长者' as const),
    assigned_caregiver_id: item.cgId,
    assigned_caregiver_name: item.cgName,
    emergency_contact: {
      name: `${item.name.charAt(0)}立强`,
      relation: '家属',
      phone: `13912${500000 + item.id * 137}`,
      address: '演示市城南示范区人民路东汇花园',
    },
    chronic_diseases: ['高血压病', '脑供血不足'],
    care_risk_tags: item.ltc === '重度失能' ? ['防压疮重点', '高跌倒风险'] : ['慢病管理'],
    devices: {
      radar_bathroom: {
        device_id: `RD-SZ-CL-0${item.id}`,
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-60dBm)',
        last_event: '正常',
      },
      sleep_pad: {
        device_id: `SP-SZ-CL-1${item.id}`,
        online: true,
        in_bed: true,
        hr: 68 + (item.id % 8),
        br: 16 + (item.id % 4),
        leave_bed_minutes: 0,
        sleep_score: 82,
      },
      sos_button: {
        device_id: `SOS-SZ-CL-90${item.id}`,
        online: true,
        battery_pct: 90,
        alarm_active: false,
        last_test_date: '2026-09-21',
      },
    },
    monthly_service_quota: item.ltc === '重度失能' ? 20 : 15,
    monthly_service_completed: 12 + (idx % 6),
    last_service_time: '2026-09-24 14:00',
    next_service_plan: '常规上门照料服务',
  })),

  // ================= 双塔片区 (26人: 10027 ~ 10052) =================
  ...[
    { id: 27, name: '唐学文', gender: 'male', age: 83, ltc: '重度失能', live: '独居', addr: '滚绣坊 16 号 2 室', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 28, name: '冯佩华', gender: 'female', age: 86, ltc: '重度失能', live: '空巢', addr: '带城桥下塘 8 号 101 室', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 29, name: '冯守信', gender: 'male', age: 80, ltc: '中度失能', live: '独居', addr: '沧浪亭街 22 号', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 30, name: '于桂芬', gender: 'female', age: 88, ltc: '重度失能', live: '独居', addr: '网师巷 7 号 102 室', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 31, name: '于广厚', gender: 'male', age: 79, ltc: '轻度失能', live: '与子女同住', addr: '十全街南区 12 幢 301 室', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 32, name: '董海兰', gender: 'female', age: 82, ltc: '重度失能', live: '空巢', addr: '滚绣坊 48 号 2 楼', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 33, name: '董成志', gender: 'male', age: 85, ltc: '重度失能', live: '独居', addr: '带城桥下塘 26 号', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 34, name: '萧月娥', gender: 'female', age: 81, ltc: '中度失能', live: '独居', addr: '沧浪亭街 5 号 2 室', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 35, name: '萧汉生', gender: 'male', age: 77, ltc: '自理高龄', live: '独居', addr: '网师巷 19 号', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 36, name: '程淑贤', gender: 'female', age: 84, ltc: '重度失能', live: '空巢', addr: '十全街 305 号 3 楼', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 37, name: '程大伟', gender: 'male', age: 80, ltc: '中度失能', live: '与子女同住', addr: '滚绣坊 29 号 1 室', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 38, name: '曹秀敏', gender: 'female', age: 79, ltc: '轻度失能', live: '独居', addr: '带城桥弄 14 号', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 39, name: '曹定国', gender: 'male', age: 87, ltc: '重度失能', live: '独居', addr: '沧浪亭街 18 号 1 室', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 40, name: '袁秀琴', gender: 'female', age: 82, ltc: '重度失能', live: '空巢', addr: '网师巷 32 号 2 室', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 41, name: '袁有福', gender: 'male', age: 83, ltc: '中度失能', live: '独居', addr: '十全街南二村 6 幢 101 室', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 42, name: '邓玉兰', gender: 'female', age: 85, ltc: '重度失能', live: '独居', addr: '滚绣坊 62 号 2 楼', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 43, name: '邓建勋', gender: 'male', age: 78, ltc: '轻度失能', live: '与子女同住', addr: '带城桥下塘 45 号', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 44, name: '许秋霞', gender: 'female', age: 80, ltc: '中度失能', live: '独居', addr: '沧浪亭后弄 3 号', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 45, name: '许文山', gender: 'male', age: 86, ltc: '重度失能', live: '独居', addr: '网师巷 50 号 1 室', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 46, name: '沈荣华', gender: 'female', age: 83, ltc: '重度失能', live: '空巢', addr: '十全街 412 号 2 楼', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 47, name: '傅立人', gender: 'male', age: 81, ltc: '中度失能', live: '独居', addr: '滚绣坊 81 号', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 48, name: '曾文英', gender: 'female', age: 87, ltc: '重度失能', live: '独居', addr: '带城桥下塘 60 号 1 室', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 49, name: '沈家栋', gender: 'male', age: 84, ltc: '重度失能', live: '独居', addr: '沧浪亭街 35 号', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 50, name: '彭慧敏', gender: 'female', age: 76, ltc: '自理高龄', live: '与子女同住', addr: '网师巷 15 号 2 室', cgId: 'cg_shuangta_02', cgName: '张伟民' },
    { id: 51, name: '曾庆发', gender: 'male', age: 82, ltc: '中度失能', live: '空巢', addr: '十全街南一村 4 幢 202 室', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
    { id: 52, name: '苏春霞', gender: 'female', age: 85, ltc: '重度失能', live: '独居', addr: '滚绣坊 95 号', cgId: 'cg_shuangta_01', cgName: '王惠芬' },
  ].map((item) => ({
    elderly_id: `SZ-ELD-100${item.id}`,
    name: item.name,
    gender: (item.gender as 'male' | 'female'),
    age: item.age,
    id_card: `32050219410815${1000 + item.id}`,
    phone: `139127${40000 + item.id * 89}`,
    area_key: ('shuangta' as const),
    area_name: '双塔片区',
    community_name: item.addr.includes('滚绣坊') ? '滚绣坊社区网格' : item.addr.includes('带城桥') ? '带城桥社区网格' : item.addr.includes('网师') ? '网师巷社区网格' : '沧浪亭社区网格',
    home_address: item.addr,
    has_elevator: false,
    floor_number: Number(item.addr.match(/\d+ 楼/)?.[0]?.charAt(0) || 1),
    ltc_level: (item.ltc as any),
    living_status: (item.live as any),
    current_state: item.id === 28 ? ('异常预警' as const) : ('在家长者' as const),
    assigned_caregiver_id: item.cgId,
    assigned_caregiver_name: item.cgName,
    emergency_contact: {
      name: `${item.name.charAt(0)}永明`,
      relation: '子女',
      phone: `138129${50000 + item.id * 73}`,
      address: '演示市城南示范区十全街商住区',
    },
    chronic_diseases: ['慢性心功能不全', '腰腿疼痛'],
    care_risk_tags: item.ltc === '重度失能' ? ['防压疮翻身', '防跌倒重点'] : ['慢病巡查'],
    devices: {
      radar_bathroom: {
        device_id: `RD-SZ-ST-0${item.id}`,
        online: true,
        presence: false,
        fall_alert: item.id === 28,
        signal_strength: '强 (-58dBm)',
        last_event: item.id === 28 ? '卫浴微动异常' : '正常',
      },
      sleep_pad: {
        device_id: `SP-SZ-ST-1${item.id}`,
        online: true,
        in_bed: true,
        hr: 70,
        br: 17,
        leave_bed_minutes: 0,
        sleep_score: 80,
      },
      sos_button: {
        device_id: `SOS-SZ-ST-90${item.id}`,
        online: true,
        battery_pct: 92,
        alarm_active: false,
        last_test_date: '2026-09-22',
      },
    },
    monthly_service_quota: item.ltc === '重度失能' ? 20 : 15,
    monthly_service_completed: 14,
    last_service_time: '2026-09-24 16:00',
    next_service_plan: '双塔组日常入户工单',
  })),

  // ================= 三香片区 (20人: 10053 ~ 10072) =================
  ...[
    { id: 53, name: '彭绍华', gender: 'male', age: 81, ltc: '重度失能', live: '独居', addr: '三香新村北区 15 幢 401 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 54, name: '卢德芳', gender: 'female', age: 86, ltc: '重度失能', live: '空巢', addr: '三香新村南区 22 幢 102 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 55, name: '苏德良', gender: 'male', age: 84, ltc: '重度失能', live: '独居', addr: '体育场路 6 号 101 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 56, name: '蒋佩兰', gender: 'female', age: 80, ltc: '中度失能', live: '与子女同住', addr: '盘溪新村 18 幢 201 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 57, name: '卢伯成', gender: 'male', age: 82, ltc: '中度失能', live: '独居', addr: '三香新村北区 28 幢 302 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 58, name: '贾金凤', gender: 'female', age: 85, ltc: '重度失能', live: '空巢', addr: '体育场路 19 号 2 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 59, name: '蒋天锡', gender: 'male', age: 87, ltc: '重度失能', live: '独居', addr: '盘溪新村 32 幢 101 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 60, name: '魏宝琴', gender: 'female', age: 79, ltc: '轻度失能', live: '独居', addr: '新市路 118 号 3 楼', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 61, name: '蔡宏达', gender: 'male', age: 83, ltc: '重度失能', live: '独居', addr: '三香新村南区 8 幢 202 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 62, name: '薛秀芹', gender: 'female', age: 81, ltc: '中度失能', live: '空巢', addr: '盘溪新村 45 幢 202 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 63, name: '贾耀东', gender: 'male', age: 78, ltc: '自理高龄', live: '与子女同住', addr: '体育场路 28 号 1 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 64, name: '余秀华', gender: 'female', age: 84, ltc: '重度失能', live: '独居', addr: '三香新村北区 36 幢 101 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 65, name: '魏长春', gender: 'male', age: 82, ltc: '重度失能', live: '空巢', addr: '新市路 205 号 2 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 66, name: '杜桂兰', gender: 'female', age: 88, ltc: '重度失能', live: '独居', addr: '盘溪新村 12 幢 102 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 67, name: '薛国安', gender: 'male', age: 79, ltc: '轻度失能', live: '独居', addr: '体育场弄 14 号', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 68, name: '戴美华', gender: 'female', age: 80, ltc: '中度失能', live: '与子女同住', addr: '三香新村南区 14 幢 301 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 69, name: '阎希明', gender: 'male', age: 85, ltc: '重度失能', live: '独居', addr: '盘溪新村 56 幢 201 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
    { id: 70, name: '夏淑贞', gender: 'female', age: 83, ltc: '重度失能', live: '空巢', addr: '新市路 88 号 2 楼', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 71, name: '余保平', gender: 'male', age: 81, ltc: '中度失能', live: '独居', addr: '三香新村北区 5 幢 201 室', cgId: 'cg_sanxiang_01', cgName: '何丽娜' },
    { id: 72, name: '田玉珍', gender: 'female', age: 86, ltc: '重度失能', live: '独居', addr: '盘溪新村 68 幢 101 室', cgId: 'cg_sanxiang_02', cgName: '赵淑清' },
  ].map((item) => ({
    elderly_id: `SZ-ELD-100${item.id}`,
    name: item.name,
    gender: (item.gender as 'male' | 'female'),
    age: item.age,
    id_card: `32050219420921${1000 + item.id}`,
    phone: `137719${30000 + item.id * 61}`,
    area_key: ('sanxiang' as const),
    area_name: '三香片区',
    community_name: item.addr.includes('三香') ? '三香社区网格' : item.addr.includes('盘溪') ? '盘溪社区网格' : item.addr.includes('体育场') ? '体育场社区网格' : '新市路网格',
    home_address: item.addr,
    has_elevator: false,
    floor_number: Number(item.addr.match(/\d+ 楼|\d+ 室/)?.[0]?.charAt(0) || 1),
    ltc_level: (item.ltc as any),
    living_status: (item.live as any),
    current_state: item.id === 53 ? ('异常预警' as const) : ('在家长者' as const),
    assigned_caregiver_id: item.cgId,
    assigned_caregiver_name: item.cgName,
    emergency_contact: {
      name: `${item.name.charAt(0)}家骏`,
      relation: '儿子',
      phone: `139625${60000 + item.id * 47}`,
      address: '演示市城南示范区三香路金茂商圈',
    },
    chronic_diseases: ['帕金森综合征', '高血压病III期', '慢阻肺'],
    care_risk_tags: item.ltc === '重度失能' ? ['防压疮护理', '慢病血压血氧监测'] : ['生活起居照护'],
    devices: {
      radar_bathroom: {
        device_id: `RD-SZ-SX-0${item.id}`,
        online: true,
        presence: false,
        fall_alert: false,
        signal_strength: '强 (-57dBm)',
        last_event: '正常',
      },
      sleep_pad: {
        device_id: `SP-SZ-SX-1${item.id}`,
        online: true,
        in_bed: true,
        hr: item.id === 53 ? 98 : 72,
        br: item.id === 53 ? 24 : 17,
        leave_bed_minutes: 0,
        sleep_score: item.id === 53 ? 65 : 82,
      },
      sos_button: {
        device_id: `SOS-SZ-SX-90${item.id}`,
        online: true,
        battery_pct: 95,
        alarm_active: false,
        last_test_date: '2026-09-23',
      },
    },
    monthly_service_quota: item.ltc === '重度失能' ? 20 : 15,
    monthly_service_completed: 15,
    last_service_time: '2026-09-24 15:00',
    next_service_plan: '三香组慢病巡检与生命体征监测',
  })),
]

// 待办工单与服务记录数据集
export interface HomeWorkOrder {
  order_id: string
  elderly_id: string
  elderly_name: string
  area_key: 'canglang' | 'shuangta' | 'sanxiang'
  area_name: string
  home_address: string
  service_code: string
  service_name: string
  caregiver_id: string
  caregiver_name: string
  caregiver_role: string
  scheduled_time: string
  status: 'pending_dispatch' | 'accepted' | 'en_route' | 'serving' | 'completed' | 'verified' | 'urgent_alert'
  duration_minutes: number
  ltc_fund_subsidy: number
  checkin_location?: string
  checkin_time?: string
  checkout_time?: string
  satisfaction_score?: number
  remarks?: string
}

export const HOME_WORK_ORDERS: HomeWorkOrder[] = [
  {
    order_id: 'WO-20260925-0101',
    elderly_id: 'SZ-ELD-10007',
    elderly_name: '郭振华',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '沧浪新村 18 幢 402 室',
    service_code: 'SAFE-01',
    service_name: '毫米波跌倒应急入户排查与急救处置',
    caregiver_id: 'demo_caregiver_03',
    caregiver_name: '黄建国',
    caregiver_role: '当值机动助老员',
    scheduled_time: '今日 07:45',
    status: 'en_route',
    duration_minutes: 30,
    ltc_fund_subsidy: 60.0,
    checkin_location: '沧浪新村 18 幢 GPS 打卡 (前往途中)',
    remarks: '系统自动联动雷达突发下坠触发紧急工单，调度中心苏怡督办',
  },
  {
    order_id: 'WO-20260925-0102',
    elderly_id: 'SZ-ELD-10001',
    elderly_name: '张卫国',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '沧浪新村 12 幢 302 室',
    service_code: 'LTC-01',
    service_name: '床上温水擦浴与更衣照料',
    caregiver_id: 'demo_grid_caregiver_01',
    caregiver_name: '林小燕',
    caregiver_role: '高级助老员',
    scheduled_time: '今日 09:30 - 10:15',
    status: 'accepted',
    duration_minutes: 45,
    ltc_fund_subsidy: 65.0,
    remarks: '重度失能规定生活照料包',
  },
  {
    order_id: 'WO-20260925-0103',
    elderly_id: 'SZ-ELD-10002',
    elderly_name: '孙秀珍',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '竹辉新村 28 幢 101 室',
    service_code: 'LTC-05',
    service_name: '大小便失禁排泄照料与认知症看护',
    caregiver_id: 'demo_caregiver_02',
    caregiver_name: '陈秀英',
    caregiver_role: '中级养老照护师',
    scheduled_time: '今日 08:30 - 09:10',
    status: 'serving',
    duration_minutes: 40,
    ltc_fund_subsidy: 50.0,
    checkin_time: '08:28 (NFC门禁打卡已核验)',
    checkin_location: '竹辉新村 28 幢 101 室门牌定位',
    remarks: '离床超时预警，助老员已入户现场看护中',
  },
  {
    order_id: 'WO-20260925-0104',
    elderly_id: 'SZ-ELD-10003',
    elderly_name: '李德海',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '沧浪新村 7 幢 201 室',
    service_code: 'LTC-06',
    service_name: '协助下床及轮椅转移功能康复',
    caregiver_id: 'demo_grid_caregiver_01',
    caregiver_name: '林小燕',
    caregiver_role: '高级助老员',
    scheduled_time: '今日 10:45 - 11:15',
    status: 'accepted',
    duration_minutes: 30,
    ltc_fund_subsidy: 35.0,
  },
  {
    order_id: 'WO-20260925-0105',
    elderly_id: 'SZ-ELD-10027',
    elderly_name: '唐学文',
    area_key: 'shuangta',
    area_name: '双塔片区',
    home_address: '滚绣坊 16 号 2 室',
    service_code: 'LTC-04',
    service_name: '协助翻身叩背及防压疮皮肤护理',
    caregiver_id: 'cg_shuangta_01',
    caregiver_name: '王惠芬',
    caregiver_role: '双塔组长',
    scheduled_time: '今日 09:00 - 09:35',
    status: 'serving',
    duration_minutes: 35,
    ltc_fund_subsidy: 45.0,
    checkin_time: '08:58 (基站定位双向认证)',
    checkin_location: '滚绣坊 16 号门牌',
  },
  {
    order_id: 'WO-20260925-0106',
    elderly_id: 'SZ-ELD-10028',
    elderly_name: '冯佩华',
    area_key: 'shuangta',
    area_name: '双塔片区',
    home_address: '带城桥下塘 8 号 101 室',
    service_code: 'LTC-07',
    service_name: '日常生命体征监测与防跌倒雷达校准',
    caregiver_id: 'cg_shuangta_01',
    caregiver_name: '王惠芬',
    caregiver_role: '双塔组长',
    scheduled_time: '今日 10:15 - 10:45',
    status: 'accepted',
    duration_minutes: 30,
    ltc_fund_subsidy: 35.0,
  },
  {
    order_id: 'WO-20260925-0107',
    elderly_id: 'SZ-ELD-10053',
    elderly_name: '彭绍华',
    area_key: 'sanxiang',
    area_name: '三香片区',
    home_address: '三香新村北区 15 幢 401 室',
    service_code: 'LTC-07',
    service_name: '慢病血压脉搏血氧监测与防心衰指导',
    caregiver_id: 'cg_sanxiang_01',
    caregiver_name: '何丽娜',
    caregiver_role: '慢病照护专员',
    scheduled_time: '今日 09:15 - 09:45',
    status: 'serving',
    duration_minutes: 30,
    ltc_fund_subsidy: 35.0,
    checkin_time: '09:12',
    checkin_location: '三香新村北区 15 幢',
  },
  {
    order_id: 'WO-20260925-0108',
    elderly_id: 'SZ-ELD-10054',
    elderly_name: '卢德芳',
    area_key: 'sanxiang',
    area_name: '三香片区',
    home_address: '三香新村南区 22 幢 102 室',
    service_code: 'LTC-01',
    service_name: '床上温水擦浴与更衣照料',
    caregiver_id: 'cg_sanxiang_01',
    caregiver_name: '何丽娜',
    caregiver_role: '慢病照护专员',
    scheduled_time: '今日 10:30 - 11:15',
    status: 'accepted',
    duration_minutes: 45,
    ltc_fund_subsidy: 65.0,
  },
  {
    order_id: 'WO-20260924-0091',
    elderly_id: 'SZ-ELD-10005',
    elderly_name: '杨保国',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '沧浪新村 35 幢 102 室',
    service_code: 'LTC-04',
    service_name: '全身翻身防压疮护理与呼吸道维护',
    caregiver_id: 'demo_caregiver_02',
    caregiver_name: '陈秀英',
    caregiver_role: '中级养老照护师',
    scheduled_time: '2026-09-24 09:00',
    status: 'verified',
    duration_minutes: 35,
    ltc_fund_subsidy: 45.0,
    checkin_time: '08:58',
    checkout_time: '09:36',
    satisfaction_score: 5,
    remarks: '医保长护险反虚构交叉验证已通过，准予核销',
  },
  // ==================== 多学科专业团队 (IDT) 与质控工单 ====================
  {
    order_id: 'WO-MED-20260925-0201',
    elderly_id: 'SZ-ELD-10026',
    elderly_name: '钱桂珍',
    area_key: 'shuangta',
    area_name: '双塔片区',
    home_address: '双塔新村 8 幢 101 室',
    service_code: 'LTC-10',
    service_name: '留置导尿管定期置换与膀胱冲洗造口护理',
    caregiver_id: 'demo_nurse_shen',
    caregiver_name: '沈雅萍',
    caregiver_role: '主管护师',
    scheduled_time: '今日 14:00 - 15:00',
    status: 'serving',
    duration_minutes: 60,
    ltc_fund_subsidy: 95.0,
    checkin_time: '13:58 (护师资质身份认证)',
    checkin_location: '双塔新村 8 幢 101 室',
    remarks: '重度失能医疗专科护理，已双人核对导尿包批号',
  },
  {
    order_id: 'WO-MED-20260925-0202',
    elderly_id: 'SZ-ELD-10006',
    elderly_name: '胡广德',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '竹辉新村 12 幢 201 室',
    service_code: 'LTC-11',
    service_name: '骶尾部IV期复杂压疮清创换药与水胶体敷料维护',
    caregiver_id: 'demo_nurse_shen',
    caregiver_name: '沈雅萍',
    caregiver_role: '主管护师',
    scheduled_time: '今日 15:30 - 16:15',
    status: 'accepted',
    duration_minutes: 45,
    ltc_fund_subsidy: 85.0,
    remarks: '伤口造口专科治疗师巡诊，评估创面肉芽生长',
  },
  {
    order_id: 'WO-PT-20260925-0203',
    elderly_id: 'SZ-ELD-10027',
    elderly_name: '孙阿祥',
    area_key: 'shuangta',
    area_name: '双塔片区',
    home_address: '滚绣坊 22 号 202 室',
    service_code: 'LTC-12',
    service_name: '脑卒中偏瘫肢体综合运动训练与防肌肉萎缩促活',
    caregiver_id: 'pt_chenjianxin',
    caregiver_name: '陈建新',
    caregiver_role: '主管康复师',
    scheduled_time: '今日 10:00 - 10:50',
    status: 'serving',
    duration_minutes: 50,
    ltc_fund_subsidy: 80.0,
    checkin_time: '09:58',
    checkin_location: '滚绣坊 22 号',
    remarks: '患侧下肢肌力提升至3+级，已指导家属辅助转移手法',
  },
  {
    order_id: 'WO-DEM-20260925-0204',
    elderly_id: 'SZ-ELD-10002',
    elderly_name: '孙秀珍',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '西美巷 28 号 101 室',
    service_code: 'LTC-14',
    service_name: '重度阿尔茨海默病怀旧感官刺激与防走失预警管理',
    caregiver_id: 'dementia_zhufang',
    caregiver_name: '朱芳',
    caregiver_role: '记忆专护师',
    scheduled_time: '今日 14:30 - 15:30',
    status: 'accepted',
    duration_minutes: 60,
    ltc_fund_subsidy: 75.0,
    remarks: '蒙台梭利老年失智干预，设定智能门磁与雷达防游走围栏',
  },
  {
    order_id: 'WO-AST-20260925-0205',
    elderly_id: 'SZ-ELD-10007',
    elderly_name: '郭振华',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '沧浪新村 18 幢 402 室',
    service_code: 'SAFE-02',
    service_name: '突发跌倒后卫浴无障碍防滑扶手加装与毫米波雷达校准',
    caregiver_id: 'tech_zhanghongbo',
    caregiver_name: '张洪波',
    caregiver_role: '适老工程师',
    scheduled_time: '今日 16:00 - 17:30',
    status: 'accepted',
    duration_minutes: 90,
    ltc_fund_subsidy: 120.0,
    remarks: '适老无障碍紧急加固，配置 L 型卫浴扶手与雷达零盲区调试',
  },
  {
    order_id: 'WO-QC-20260925-0206',
    elderly_id: 'SZ-ELD-10001',
    elderly_name: '赵金宝',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '沧浪新村 12 幢 302 室',
    service_code: 'QC-01',
    service_name: '助老员床上擦浴服务规范双盲入户飞行质量检查',
    caregiver_id: 'qc_jiangguoqiang',
    caregiver_name: '蒋国强',
    caregiver_role: '质控主管',
    scheduled_time: '今日 09:30 - 10:00',
    status: 'verified',
    duration_minutes: 30,
    ltc_fund_subsidy: 0.0,
    checkin_time: '09:28',
    checkout_time: '09:58',
    satisfaction_score: 5,
    remarks: '现场抽检助老员林小燕服务全流程，水温40℃合规，家属高度赞许',
  },
  {
    order_id: 'WO-CM-20260925-0207',
    elderly_id: 'SZ-ELD-10003',
    elderly_name: '李德海',
    area_key: 'canglang',
    area_name: '沧浪片区',
    home_address: '道前街 120 号 203 室',
    service_code: 'CM-01',
    service_name: '“一人一策”居家多学科综合照护专案定期评估与家属随访',
    caregiver_id: 'cm_xumeiling',
    caregiver_name: '徐美玲',
    caregiver_role: '个案管理师',
    scheduled_time: '今日 11:00 - 11:45',
    status: 'accepted',
    duration_minutes: 45,
    ltc_fund_subsidy: 50.0,
    remarks: '重度失能需求动态调整，联动专职护师与康复师更新服务计划',
  },
]
