// ============================================================
// 中科安樵在册感知设备全量权威清单 —— 前端唯一权威数据源
// 整合数据源：
// 1. 宿迁医保局长护险 3 台真实设备 (ASH01086 / ASH01078 / ASH01092) 全部在线，绑定 3 位真实长者；
// 2. 中科安樵自营全量在册感知设备 (太湖科创中心、园区康养、睡眠中心、实验室样机等)。
// ============================================================

export type DeviceCategory = 'health_guardian' | 'health_monitor' | 'fall_detector' | 'unknown'

export interface AnqiaoDevice {
  sn: string
  label: string        // 点位短名
  city: string         // 如 '宿迁市' / '苏州市'
  district: string     // 如 '宿城区' / '吴中区' / '待确认'
  address: string      // 真实部署地址全量
  lon: number | null   // 经度
  lat: number | null   // 纬度
  ip: string           // IP或网络标识
  network: string      // 网络通道
  model: string        // 设备型号或产品名称
  category: DeviceCategory // 设备类别
  scene: string        // 部署场景
  online: boolean      // 在线状态
  flagship: boolean    // 是否旗舰机
  userId: number       // 绑定云账号 ID
  alias: string        // 设备别名
  latestDataTime: string | null // 云平台最后上报时间
  registered: boolean  // 固定 true
}

export const ANQIAO_DEVICES: AnqiaoDevice[] = [
  {
    "sn": "ANCE00001",
    "label": "演示·康宁国际·404",
    "city": "苏州市",
    "district": "吴中区",
    "address": "苏州市吴中区演示·康宁护理院（模拟机构）4F-404-01床",
    "lon": 120.612,
    "lat": 31.305,
    "ip": "58.211.134.52",
    "network": "专网光纤通道",
    "model": "AI健康守护仪 (ANCE-01)",
    "category": "health_guardian",
    "scene": "康养示范点",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "ANCE00001",
    "latestDataTime": "2026-09-22 08:00:00",
    "registered": true
  },
  {
    "sn": "ASH01086",
    "label": "ASH01086",
    "city": "宿迁市",
    "district": "宿城区",
    "address": "宿迁市宿城区项里街道长护险试点照护点01号",
    "lon": 118.28,
    "lat": 33.96,
    "ip": "未提供",
    "network": "物联专网 (江苏宿迁)",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "长护险居家监护",
    "online": true,
    "flagship": true,
    "userId": 55,
    "alias": "ASH01086",
    "latestDataTime": "2026-09-23 14:30:00",
    "registered": true
  },
  {
    "sn": "ASH01078",
    "label": "ASH01078",
    "city": "宿迁市",
    "district": "宿城区",
    "address": "宿迁市宿城区双庄街道长护险试点照护点02号",
    "lon": 118.27,
    "lat": 33.965,
    "ip": "未提供",
    "network": "物联专网 (江苏宿迁)",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "长护险居家监护",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "ASH01078",
    "latestDataTime": "2026-09-23 14:30:00",
    "registered": true
  },
  {
    "sn": "ASH01092",
    "label": "ASH01092",
    "city": "宿迁市",
    "district": "宿城区",
    "address": "宿迁市宿城区支口街道长护险试点照护点03号",
    "lon": 118.285,
    "lat": 33.955,
    "ip": "未提供",
    "network": "物联专网 (江苏宿迁)",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "长护险居家监护",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "ASH01092",
    "latestDataTime": "2026-09-23 14:30:00",
    "registered": true
  },
  {
    "sn": "ASH01146",
    "label": "太湖科创中心·903",
    "city": "苏州市",
    "district": "吴中区",
    "address": "苏州市吴中区藤器街太湖科创中心A座903室 (中科展厅总控)",
    "lon": 120.5998,
    "lat": 31.1638,
    "ip": "58.211.134.50",
    "network": "物联专网 (苏州专线)",
    "model": "AI健康守护仪",
    "category": "health_guardian",
    "scene": "旗舰展厅",
    "online": true,
    "flagship": true,
    "userId": 55,
    "alias": "ASH01146",
    "latestDataTime": "2026-09-22 23:56:08",
    "registered": true
  },
  {
    "sn": "ASH01076",
    "label": "园区康养·815",
    "city": "苏州市",
    "district": "苏州工业园区",
    "address": "苏州市苏州工业园区星湖街815号康养公寓8幢815室",
    "lon": 120.7208,
    "lat": 31.3152,
    "ip": "223.104.147.88",
    "network": "4G蜂窝物联网 (江苏苏州移动)",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "康养示范点",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "ASH01076",
    "latestDataTime": "2026-09-18 08:34:58",
    "registered": true
  },
  {
    "sn": "ASH01016",
    "label": "独墅湖科创区·206",
    "city": "苏州市",
    "district": "苏州工业园区",
    "address": "苏州市苏州工业园区仁爱路独墅湖科教创新区科研楼B栋206室",
    "lon": 120.7315,
    "lat": 31.2752,
    "ip": "58.211.134.53",
    "network": "专网光纤通道 (江苏苏州电信)",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "睡眠研究中心",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "ASH01016",
    "latestDataTime": "2026-08-14 02:03:42",
    "registered": true
  },
  {
    "sn": "ANCE00003",
    "label": "园区康养·613",
    "city": "苏州市",
    "district": "苏州工业园区",
    "address": "苏州市苏州工业园区星湖街613号康养公寓6幢613室",
    "lon": 120.7196,
    "lat": 31.3085,
    "ip": "223.104.147.89",
    "network": "4G蜂窝物联网 (江苏苏州移动)",
    "model": "AI健康守护仪 (ANCE-01)",
    "category": "health_guardian",
    "scene": "康养示范点",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "ANCE00003",
    "latestDataTime": "2026-05-22 23:24:41",
    "registered": true
  },
  {
    "sn": "ANCE00002",
    "label": "石湖金陵广场·301",
    "city": "苏州市",
    "district": "吴中区",
    "address": "苏州市吴中区石湖西路188号石湖金陵广场B座301室 (运维中枢)",
    "lon": 120.5856,
    "lat": 31.2389,
    "ip": "58.211.134.55",
    "network": "Wi-Fi局域网 (SSID: HF)",
    "model": "AI健康守护仪 (ANCE-01)",
    "category": "health_guardian",
    "scene": "运维中枢",
    "online": false,
    "flagship": false,
    "userId": 55,
    "alias": "ANCE00002",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01118",
    "label": "石湖金陵广场·801",
    "city": "苏州市",
    "district": "吴中区",
    "address": "苏州市吴中区石湖西路188号石湖金陵广场A座801室",
    "lon": 120.5861,
    "lat": 31.2394,
    "ip": "58.211.134.56",
    "network": "Wi-Fi局域网 (SSID: HF)",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "在册归档",
    "online": false,
    "flagship": false,
    "userId": 55,
    "alias": "ASH01118",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "X2_S01B05N962",
    "label": "太湖科创中心·901",
    "city": "苏州市",
    "district": "吴中区",
    "address": "苏州市吴中区藤器街太湖科创中心A座901室 (研发实验室)",
    "lon": 120.5992,
    "lat": 31.1633,
    "ip": "58.211.134.50",
    "network": "Wi-Fi IEEE 802.11 b/g/n 2.4GHz",
    "model": "多模态AI守护仪样机 (X2_S01)",
    "category": "health_guardian",
    "scene": "实验室",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "X2_S01B05N962",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01038",
    "label": "太湖科创中心·演示台",
    "city": "苏州市",
    "district": "吴中区",
    "address": "苏州市吴中区藤器街太湖科创中心A座9层办公区 (运营演示台)",
    "lon": 120.6004,
    "lat": 31.1643,
    "ip": "58.211.134.50",
    "network": "Wi-Fi IEEE 802.11 b/g/n 2.4GHz",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "办公演示",
    "online": true,
    "flagship": false,
    "userId": 42,
    "alias": "ASH01038",
    "latestDataTime": "2026-09-22 17:28:11",
    "registered": true
  },
  {
    "sn": "ASH01021",
    "label": "太湖科创中心·库房B",
    "city": "苏州市",
    "district": "吴中区",
    "address": "苏州市吴中区藤器街太湖科创中心A座9层设备库房B区 (2026-09-22 新装待部署)",
    "lon": 120.601,
    "lat": 31.1648,
    "ip": "58.211.134.50",
    "network": "Wi-Fi IEEE 802.11 b/g/n 2.4GHz",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "在册归档",
    "online": true,
    "flagship": false,
    "userId": 55,
    "alias": "ASH01021",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "41981890",
    "label": "41981890",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "云平台物联通道",
    "model": "健康监测仪",
    "category": "health_monitor",
    "scene": "健康体征监测",
    "online": true,
    "flagship": false,
    "userId": 41,
    "alias": "41981890",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "1C6920D123A0",
    "label": "1C6920D123A0",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "Wi-Fi局域网",
    "model": "WiFi摔倒报警器(R1)",
    "category": "fall_detector",
    "scene": "跌倒监测",
    "online": true,
    "flagship": false,
    "userId": 42,
    "alias": "1C6920D123A0",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "58757725",
    "label": "58757725",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "云平台物联通道",
    "model": "健康监测仪",
    "category": "health_monitor",
    "scene": "健康体征监测",
    "online": true,
    "flagship": false,
    "userId": 42,
    "alias": "58757725",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "862944067812863",
    "label": "862944067812863",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "4G蜂窝物联网",
    "model": "4G摔倒报警器(R1)",
    "category": "fall_detector",
    "scene": "跌倒监测",
    "online": true,
    "flagship": false,
    "userId": 42,
    "alias": "862944067812863",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01046",
    "label": "ASH01046",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 42,
    "alias": "ASH01046",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01129",
    "label": "ASH01129",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 42,
    "alias": "ASH01129",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01153",
    "label": "ASH01153",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 42,
    "alias": "ASH01153",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_001",
    "label": "device_001",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_001",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_002",
    "label": "device_002",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_002",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_003",
    "label": "device_003",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_003",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_004",
    "label": "device_004",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_004",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_005",
    "label": "device_005",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_005",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_006",
    "label": "device_006",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_006",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_007",
    "label": "device_007",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_007",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "device_008",
    "label": "device_008",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "开发测试通道",
    "model": "AI健康守护仪 (测试终端)",
    "category": "health_guardian",
    "scene": "测试调试",
    "online": false,
    "flagship": false,
    "userId": 42,
    "alias": "device_008",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ANCE00005",
    "label": "ANCE00005",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ANCE-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 63,
    "alias": "ANCE00005",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH010002",
    "label": "ASH010002",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 64,
    "alias": "ASH010002",
    "latestDataTime": "2026-09-22 23:56:05",
    "registered": true
  },
  {
    "sn": "ASH01090",
    "label": "ASH01090",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 64,
    "alias": "ASH01090",
    "latestDataTime": "2026-09-04 04:11:37",
    "registered": true
  },
  {
    "sn": "ASH01100",
    "label": "ASH01100",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 64,
    "alias": "ASH01100",
    "latestDataTime": "2026-08-16 23:20:32",
    "registered": true
  },
  {
    "sn": "ASH01006",
    "label": "ASH01006",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 68,
    "alias": "ASH01006",
    "latestDataTime": "2026-09-22 23:56:07",
    "registered": true
  },
  {
    "sn": "ASH01023",
    "label": "ASH01023",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 68,
    "alias": "ASH01023",
    "latestDataTime": "2026-07-31 22:11:05",
    "registered": true
  },
  {
    "sn": "ASH01028",
    "label": "ASH01028",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 68,
    "alias": "ASH01028",
    "latestDataTime": "2026-09-13 21:15:33",
    "registered": true
  },
  {
    "sn": "ASH01059",
    "label": "ASH01059",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 68,
    "alias": "ASH01059",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01042",
    "label": "ASH01042",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 70,
    "alias": "ASH01042",
    "latestDataTime": "2026-07-26 01:56:29",
    "registered": true
  },
  {
    "sn": "ASH01025",
    "label": "ASH01025",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 71,
    "alias": "ASH01025",
    "latestDataTime": "2026-07-27 04:05:17",
    "registered": true
  },
  {
    "sn": "ASH01037",
    "label": "ASH01037",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 73,
    "alias": "ASH01037",
    "latestDataTime": "2026-07-29 20:46:32",
    "registered": true
  },
  {
    "sn": "ASH01036",
    "label": "ASH01036",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 77,
    "alias": "ASH01036",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01047",
    "label": "ASH01047",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 78,
    "alias": "ASH01047",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01030",
    "label": "ASH01030",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 80,
    "alias": "ASH01030",
    "latestDataTime": "2026-08-18 23:06:28",
    "registered": true
  },
  {
    "sn": "ASH01039",
    "label": "ASH01039",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 80,
    "alias": "ASH01039",
    "latestDataTime": "2026-09-06 08:34:58",
    "registered": true
  },
  {
    "sn": "ASH01033",
    "label": "ASH01033",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 102,
    "alias": "ASH01033",
    "latestDataTime": "2026-08-09 20:01:07",
    "registered": true
  },
  {
    "sn": "ASH01044",
    "label": "ASH01044",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 131,
    "alias": "ASH01044",
    "latestDataTime": "2026-08-22 08:34:56",
    "registered": true
  },
  {
    "sn": "ASH01166",
    "label": "ASH01166",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 139,
    "alias": "ASH01166",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01029",
    "label": "ASH01029",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 141,
    "alias": "ASH01029",
    "latestDataTime": null,
    "registered": true
  },
  {
    "sn": "ASH01156",
    "label": "ASH01156",
    "city": "苏州市",
    "district": "待确认",
    "address": "地址待确认",
    "lon": null,
    "lat": null,
    "ip": "未提供",
    "network": "物联专网",
    "model": "AI健康守护仪 (ASH-01)",
    "category": "health_guardian",
    "scene": "居家在册",
    "online": true,
    "flagship": false,
    "userId": 144,
    "alias": "ASH01156",
    "latestDataTime": "2026-09-22 17:31:27",
    "registered": true
  }
]

export function getAnqiaoDevice(sn: string): AnqiaoDevice | undefined {
  return ANQIAO_DEVICES.find((d) => d.sn === sn)
}

export const ANQIAO_ONLINE_COUNT: number = ANQIAO_DEVICES.filter((d) => d.online).length
